# ===================================== DATASET ====================================================
DATASET: 'WaymoDataset'

DATA_PATH: '/media/slammot/data/data/waymo'
PROCESSED_DATA_TAG: 'waymo_processed_data_train_val_test'

DATA_SPLIT: {
    'train': train,
    'test': val   # val  test
}

class_names: ['Vehicle', 'Pedestrian', 'Cyclist']
save_path: "output"

# -------------------------------------- Public Detector ---------------------------------
public_detector: False
public_detections: "data/KITTI/detection/casa_Car_training"


# ------------------------------------ Hyperparamenters ---------------------------------
confidence_his_max: 9  #9
max_ages: 48  #33
Vehicle:
  min_frames: 1  #2
  confidence_threshold: 0.3

Pedestrian:
  min_frames: 1
  confidence_threshold: 0.1

Cyclist:
  min_frames: 1
  confidence_threshold: 0.1


# --------------------------------------- 2D Detector -------------------------------------
detector_name_2d: "FasterRCNN"   # MaskRCNN  FasterRCNN
FasterRCNN:
  num_classes: 4
  ckpt: "weights/FasterRCNN/waymo/resNetFpn-model-15.pth"  #  weights/FasterRCNN/resNetFpn-model.pth"
MaskRCNN:
  num_classes: 91
  ckpt: "detector/mask_rcnn/maskrcnn_resnet50_fpn_coco.pth"


# ---------------------------------------- 3D Detector -------------------------------------
detector_name_3d: "PCDet"  # CasA  TED  PCDet
pcdet_yaml: PV-RCNN

CASA:
  cfg: "detector/CasA/tools/cfgs/waymo_models/CasA-V-Center.yaml"
  ckpt: "weights/CasA/waymo_casa/Waymo_CasA-V-Center.pth"
PCDet:
  PV-RCNN:
      cfg: "detector/pcdet/tools/cfgs/waymo_models/pv_rcnn_plusplus_resnet.yaml"
      ckpt: "/home/slammot/Desktop/CodeFIle/OpenPCDet-master/output/cfgs/waymo_models/pv_rcnn_plusplus_resnet/default/ckpt/checkpoint_epoch_30.pth"
  Voxel-RCNN:
      cfg: "detector/pcdet/tools/cfgs/waymo_models/voxel_rcnn_with_centerhead_dyn_voxel.yaml"
  PartA2-Net:
      cfg: "detector/pcdet/tools/cfgs/waymo_models/PartA2.yaml"


# --------------------------------- paramenters of detector -----------------------------------
SAMPLED_INTERVAL: {
    'train': 5,
    'test': 1
}
POINT_CLOUD_RANGE: [-75.2, -75.2, -2, 75.2, 75.2, 4]
FILTER_EMPTY_BOXES_FOR_TRAIN: True
DISABLE_NLZ_FLAG_ON_POINTS: True

USE_SHARED_MEMORY: False  # it will load the data to shared memory to speed up (DO NOT USE IT IF YOU DO NOT FULLY UNDERSTAND WHAT WILL HAPPEN)
SHARED_MEMORY_FILE_LIMIT: 35000  # set it based on the size of your shared memory

DATA_AUGMENTOR:
    DISABLE_AUG_LIST: ['placeholder']
    AUG_CONFIG_LIST:
        - NAME: gt_sampling
          USE_ROAD_PLANE: False
          DB_INFO_PATH:
              - waymo_processed_data_v0_5_0_waymo_dbinfos_train_sampled_1.pkl

          USE_SHARED_MEMORY: False  # set it to True to speed up (it costs about 15GB shared memory)
          DB_DATA_PATH:
              - waymo_processed_data_v0_5_0_gt_database_train_sampled_1_global.npy

          BACKUP_DB_INFO:
              # if the above DB_INFO cannot be found, will use this backup one
              DB_INFO_PATH: waymo_processed_data_v0_5_0_waymo_dbinfos_train_sampled_1_multiframe_-4_to_0.pkl
              DB_DATA_PATH: waymo_processed_data_v0_5_0_gt_database_train_sampled_1_multiframe_-4_to_0_global.npy
              NUM_POINT_FEATURES: 6

          PREPARE: {
             filter_by_min_points: ['Vehicle:5', 'Pedestrian:5', 'Cyclist:5'],
             filter_by_difficulty: [-1],
          }

          SAMPLE_GROUPS: ['Vehicle:15', 'Pedestrian:10', 'Cyclist:10']
          NUM_POINT_FEATURES: 5
          REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
          LIMIT_WHOLE_SCENE: True

        - NAME: random_world_flip
          ALONG_AXIS_LIST: ['x', 'y']

        - NAME: random_world_rotation
          WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

        - NAME: random_world_scaling
          WORLD_SCALE_RANGE: [0.95, 1.05]


POINT_FEATURE_ENCODING: {
    encoding_type: absolute_coordinates_encoding,
    used_feature_list: ['x', 'y', 'z', 'intensity', 'elongation'],
    src_feature_list: ['x', 'y', 'z', 'intensity', 'elongation'],
}


DATA_PROCESSOR:
    - NAME: mask_points_and_boxes_outside_range
      REMOVE_OUTSIDE_BOXES: True

    - NAME: shuffle_points
      SHUFFLE_ENABLED: {
        'train': True,
        'test': True
      }

    - NAME: transform_points_to_voxels
      VOXEL_SIZE: [0.1, 0.1, 0.15]
      MAX_POINTS_PER_VOXEL: 5
      MAX_NUMBER_OF_VOXELS: {
        'train': 150000,
        'test': 150000
      }
